-- MySQL Script generated by MySQL Workbench
-- Wed Oct 30 17:48:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EscapeRoom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EscapeRoom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EscapeRoom` DEFAULT CHARACTER SET utf8mb4 ;
USE `EscapeRoom` ;

-- -----------------------------------------------------
-- Table `EscapeRoom`.`escape_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EscapeRoom`.`escape_room` (
  `id_escape_room` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id_escape_room`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EscapeRoom`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EscapeRoom`.`room` (
  `id_room` INT NOT NULL AUTO_INCREMENT,
  `escape_room_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `difficulty_level` INT NOT NULL,
  `theme` VARCHAR(45) NOT NULL,
  `escape_room_id_escape_room` INT NOT NULL,
  PRIMARY KEY (`id_room`),
  INDEX `fk_room_escape_room1_idx` (`escape_room_id_escape_room` ASC) VISIBLE,
  CONSTRAINT `fk_room_escape_room1`
    FOREIGN KEY (`escape_room_id_escape_room`)
    REFERENCES `EscapeRoom`.`escape_room` (`id_escape_room`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EscapeRoom`.`hint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EscapeRoom`.`hint` (
  `id_hint` INT NOT NULL AUTO_INCREMENT,
  `theme` VARCHAR(45) NOT NULL,
  `room_id` INT NULL,
  `details` VARCHAR(45) NULL,
  `room_id_room` INT NOT NULL,
  PRIMARY KEY (`id_hint`),
  INDEX `fk_hint_room1_idx` (`room_id_room` ASC) VISIBLE,
  CONSTRAINT `fk_hint_room1`
    FOREIGN KEY (`room_id_room`)
    REFERENCES `EscapeRoom`.`room` (`id_room`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EscapeRoom`.`decoration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EscapeRoom`.`decoration` (
  `id_decoration` INT NOT NULL AUTO_INCREMENT,
  `room_id` INT NOT NULL,
  `material_type` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `room_id_room` INT NOT NULL,
  PRIMARY KEY (`id_decoration`),
  INDEX `fk_decoration_room1_idx` (`room_id_room` ASC) VISIBLE,
  CONSTRAINT `fk_decoration_room1`
    FOREIGN KEY (`room_id_room`)
    REFERENCES `EscapeRoom`.`room` (`id_room`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EscapeRoom`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EscapeRoom`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `achievements` VARCHAR(45) NOT NULL,
  `escape_room_id_escape_room` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_user_escape_room1_idx` (`escape_room_id_escape_room` ASC) VISIBLE,
  CONSTRAINT `fk_user_escape_room1`
    FOREIGN KEY (`escape_room_id_escape_room`)
    REFERENCES `EscapeRoom`.`escape_room` (`id_escape_room`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EscapeRoom`.`certificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EscapeRoom`.`certificate` (
  `id_certificate` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `achievement_details` VARCHAR(45) NULL,
  `award_date` DATE NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_certificate`),
  INDEX `fk_certificate_user1_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_certificate_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `EscapeRoom`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EscapeRoom`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EscapeRoom`.`ticket` (
  `id_ticket` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `sale_date` DATE NOT NULL,
  `amount` DECIMAL(10,2) NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_ticket`),
  INDEX `fk_ticket_user1_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `EscapeRoom`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
